[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn proxy_server:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 --access-logfile - --error-logfile -"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
